### PR TITLE
Re-fix CI

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
I am seeing that travis-ci is activated for this repository but no travis.yml exists, and it should have been there. Fixing that

### CODE REVIEW

**Comment by fgei** [comment]
thanks @MSF-Jarvis for the PR
just a quick question on the travis.yml, why did you change the build tools to 22.0.1 and the compile sdk to 22?

**Comment by MSF-Jarvis** [comment]
I'm not sure anymore, apparently did this in a daze, I'll hopefully get the
build tools and everything updated and ready to build in a couple of days,
currently not at home.

**Comment by MSF-Jarvis** [comment]
@fgei Orbot is using android-22, I can't help it since we're tracking it as a git submodule

**Comment by subsymbolic** [comment]
Thanks for submitting this. CI has been added in subsequent work so I'll close this off now. Thanks again.

**Pull request closed without merging**
