### PR TITLE
Lithuanian translation added

### PR DESCRIPTION
**Pull request by zygimantus**

### CODE REVIEW

**Comment by fgei** [comment]
thanks @zygimantus can you also add these missing strings:
@mueller-ma can you please add these strings too:
<string name="SearchStringSmall">Search DDG or type URL</string>
<string name="SearchStringBig">Search DuckDuckGo or type URL</string>

also, there's a few empty strings, can you translate or remove them?
thanks!

**Comment by zygimantus** [comment]
@fgei I cannot find those strings, what are their keys?

**Comment by fgei** [comment]
sorry @zygimantus I forgot to add that!
the keys are: name="SearchStringSmall" and name="SearchStringBig", you can find them in the string.xml file in values

**Comment by subsymbolic** [comment]
Thank you for submitting this. Sadly we can't accept contributions at the moment. We have a new project in the early stages of development at https://github.com/duckduckgo/android and will be accepting contributions there in the future. Thanks again!

**Pull request closed without merging**
