### PR TITLE
optipng-ed .png files

### PR DESCRIPTION
**Pull request by m4sk1n**
Just to make DuckDuckGo app a bit smaller 😆

### CODE REVIEW

**Comment by m4sk1n** [comment]
@fgei

**Comment by fgei** [comment]
@m4sk1n some strings are referenced in the wrong way
example: "action_settings" value is "\@string/settings" you should definitely remove the "\"

**Comment by m4sk1n** [comment]
@fgei now it should be fine, I have no idea why it happened

**Comment by fgei** [comment]
thanks @m4sk1n, merging now!

**Pull request merged**
