### PR TITLE
updated german translation + text formatting

### PR DESCRIPTION
**Pull request by mueller-ma**
- Updated german translation
- Javascript => JavaScript
- Replaced tabs with 4 spaces
- Removed spaces in empty lines

### CODE REVIEW

**Comment by fgei** [comment]
@mueller-ma can you please add these strings too:
<string name="SearchStringSmall">Search DDG or type URL</string>
<string name="SearchStringBig">Search DuckDuckGo or type URL</string>

thanks!

**Comment by mueller-ma** [comment]
@fgei done
Where is "SearchString" and why isn't it in values/strings.xml?

**Comment by fgei** [comment]
@mueller-ma we removed SearchString and replaced it with SearchStringSmall and SearchStringBig

**Comment by fgei** [comment]
thanks @mueller-ma merging this now!

**Pull request merged**
